fix: add error when unable to parse project name from meson.build

diff --git a/mesmer b/mesmer
--- a/mesmer
+++ b/mesmer
@@ -102,7 +102,12 @@ meson_extract_project_name() {
 
     esac
 
-    printf "%s" "$project_name"
+    if [ -n "$project_name" ]; then
+        printf "${colorRed}Error:${colorNone} could not find project name from meson.build\n"
+        exit 1
+    else
+        printf "%s" "$project_name"
+    fi
 }
 
 checkDebug() {
